export default {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'cdd6f4', background: '1e1e2e' },
    { token: 'invalid', foreground: 'f38ba8' },
    { token: 'emphasis', fontStyle: 'italic' },
    { token: 'strong', fontStyle: 'bold' },

    { token: 'variable', foreground: '89b4fa' },
    { token: 'variable.predefined', foreground: '74c7ec' },
    { token: 'constant', foreground: 'fab387' },
    { token: 'comment', foreground: '6c7086' },
    { token: 'number', foreground: 'fab387' },
    { token: 'number.hex', foreground: 'f5c2e7' },
    { token: 'regexp', foreground: 'f38ba8' },
    { token: 'annotation', foreground: 'a6adc8' },
    { token: 'type', foreground: 'f9e2af' },

    { token: 'delimiter', foreground: '9399b2' },
    { token: 'delimiter.html', foreground: '9399b2' },
    { token: 'delimiter.xml', foreground: '89b4fa' },

    { token: 'tag', foreground: 'f38ba8' },
    { token: 'tag.id.pug', foreground: '89b4fa' },
    { token: 'tag.class.pug', foreground: '89b4fa' },
    { token: 'meta.scss', foreground: 'f38ba8' },
    { token: 'metatag', foreground: 'fab387' },
    { token: 'metatag.content.html', foreground: 'a6e3a1' },
    { token: 'metatag.html', foreground: '9399b2' },
    { token: 'metatag.xml', foreground: '9399b2' },
    { token: 'metatag.php', fontStyle: 'bold' },

    { token: 'key', foreground: '89b4fa' },
    { token: 'string.key.json', foreground: '89b4fa' },
    { token: 'string.value.json', foreground: 'a6e3a1' },

    { token: 'attribute.name', foreground: 'f9e2af' },
    { token: 'attribute.value', foreground: 'a6e3a1' },
    { token: 'attribute.value.number', foreground: 'fab387' },
    { token: 'attribute.value.unit', foreground: 'fab387' },
    { token: 'attribute.value.html', foreground: 'a6e3a1' },
    { token: 'attribute.value.xml', foreground: 'a6e3a1' },

    { token: 'string', foreground: 'a6e3a1' },
    { token: 'string.html', foreground: 'a6e3a1' },
    { token: 'string.sql', foreground: 'a6e3a1' },
    { token: 'string.yaml', foreground: 'a6e3a1' },

    { token: 'keyword', foreground: 'cba6f7' },
    { token: 'keyword.json', foreground: 'cba6f7' },
    { token: 'keyword.flow', foreground: 'f5c2e7' },
    { token: 'keyword.flow.scss', foreground: 'cba6f7' },

    { token: 'operator.scss', foreground: '9399b2' },
    { token: 'operator.sql', foreground: '9399b2' },
    { token: 'operator.swift', foreground: '9399b2' },
    { token: 'predefined.sql', foreground: 'f5c2e7' },
  ],
  colors: {
    'editor.background': '#1e1e2e',
    'editor.foreground': '#cdd6f4',
    'editor.selectionBackground': '#45475a',
    'editor.inactiveSelectionBackground': '#313244',
    'editor.lineHighlightBackground': '#313244',
    'editorIndentGuide.background': '#45475a',
    'editorIndentGuide.activeBackground': '#585b70',
    'editor.selectionHighlightBackground': '#45475a80',
    'editorCursor.foreground': '#f5e0dc',
    'editorWhitespace.foreground': '#45475a',
    'editorLineNumber.foreground': '#585b70',
    'editorLineNumber.activeForeground': '#a6adc8',
    'editorWidget.background': '#181825',
    'editorWidget.border': '#313244',
    'editorSuggestWidget.background': '#181825',
    'editorSuggestWidget.border': '#313244',
    'editorSuggestWidget.selectedBackground': '#45475a',
    'editorHoverWidget.background': '#181825',
    'editorHoverWidget.border': '#313244',
    'scrollbarSlider.background': '#45475a80',
    'scrollbarSlider.hoverBackground': '#585b70',
    'scrollbarSlider.activeBackground': '#6c7086',
  },
};
