export default {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '5b4636', background: 'f4ecd8' },
    { token: 'invalid', foreground: 'b00020' },
    { token: 'comment', foreground: '8c735d', fontStyle: 'italic' },
    { token: 'variable', foreground: '325d88' },
    { token: 'variable.predefined', foreground: '3f6f78' },
    { token: 'constant', foreground: 'a34f18' },
    { token: 'number', foreground: 'a34f18' },
    { token: 'number.hex', foreground: '7b3f91' },
    { token: 'type', foreground: '6f5f00' },
    { token: 'delimiter', foreground: '725c4a' },
    { token: 'tag', foreground: '9a3146' },
    { token: 'meta.scss', foreground: '9a3146' },
    { token: 'metatag', foreground: 'a34f18' },
    { token: 'key', foreground: '325d88' },
    { token: 'attribute.name', foreground: '806000' },
    { token: 'attribute.value', foreground: '477232' },
    { token: 'attribute.value.number', foreground: 'a34f18' },
    { token: 'attribute.value.unit', foreground: 'a34f18' },
    { token: 'string', foreground: '477232' },
    { token: 'keyword', foreground: '7b3f91' },
    { token: 'operator.scss', foreground: '725c4a' },
  ],
  colors: {
    'editor.background': '#f4ecd8',
    'editor.foreground': '#5b4636',
    'editor.selectionBackground': '#d8c8aa',
    'editor.inactiveSelectionBackground': '#e6dac1',
    'editor.lineHighlightBackground': '#eee3cc',
    'editorIndentGuide.background': '#d7c7a9',
    'editorIndentGuide.activeBackground': '#b9a486',
    'editor.selectionHighlightBackground': '#d8c8aa80',
    'editorCursor.foreground': '#7b3f91',
    'editorWhitespace.foreground': '#c9b898',
    'editorWidget.background': '#f8f1df',
    'editorWidget.border': '#c9b898',
    'scrollbarSlider.background': '#b9a48680',
    'scrollbarSlider.hoverBackground': '#a78f6c99',
    'scrollbarSlider.activeBackground': '#8c735dcc',
  },
};
